# Generated by Django 4.1.4 on 2022-12-08 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Catgeory'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='catgeory_name',
            new_name='category_name',
        ),
    ]
