# Generated by Django 4.1.4 on 2022-12-08 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0001_initial'),
        ('products', '0002_alter_products_options_alter_variants_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='variants',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='variants.variants'),
        ),
        migrations.DeleteModel(
            name='Variants',
        ),
    ]
